In [1]:
import numpy as np
import xarray as xr
import pandas as pd

In [2]:
import sys
sys.path.append('./../Scripts')
import flux_area_integration as fai

In [3]:
import importlib as ilib
ilib.reload(fai)

In [4]:
Rayner = './../data/fco2_Rayner-C13-2018_June2018-ext3_1992-2012_monthlymean_XYT.nc'
df = xr.open_dataset(Rayner)

In [5]:
%%time

# clean_fai branch
fai.spatial_integration(df, ['Terrestrial_flux','ocean'])

CPU times: user 1.61 s, sys: 10.8 ms, total: 1.62 s
Wall time: 1.61 s

,time,earth_land_total,south_land_total,trop_land_total,north_land_total,earth_ocean_total,south_ocean_total,trop_ocean_total,north_ocean_total
0,1992-01-16 00:00:00,-2.43004,0.0308537,-2.17337,-0.287521,1.07793,0.943432,-0.149029,0.283523
1,1992-02-16 00:00:00,-4.21392,0.193971,-1.80941,-2.59848,0.149843,0.486222,-0.442582,0.106204
2,1992-03-16 00:00:00,-5.36311,-0.0598953,-1.23004,-4.07317,0.0661572,1.0177,-0.750011,-0.201536
3,1992-04-16 00:00:00,-0.104166,0.489597,0.373112,-0.966875,0.536587,0.880531,-0.551915,0.20797
4,1992-05-16 00:00:00,2.10811,0.288599,1.82676,-0.00724681,0.265317,0.876886,-0.129107,-0.482462
5,1992-06-16 00:00:00,-2.74327,-0.30694,-0.852089,-1.58425,-1.35972,-0.120793,-0.810533,-0.428397
6,1992-07-16 00:00:00,-8.20888,0.938441,-3.66574,-5.48157,-1.07212,-0.281311,-0.4646,-0.32621
7,1992-08-16 00:00:00,-5.02205,1.16353,-2.93622,-3.24936,-2.30409,-0.652793,-0.870858,-0.780438
8,1992-09-16 00:00:00,-2.61683,1.15009,0.135258,-3.90218,-0.798,0.187374,-0.851142,-0.134232
9,1992-10-16 00:00:00,0.94107,0.171594,0.563284,0.206192,-0.334759,0.693031,-0.365175,-0.662615
10,1992-11-16 00:00:00,-1.63412,-0.270905,0.299465,-1.66268,0.156096,0.892955,-0.286376,-0.450483
11,1992-12-16 00:00:00,-0.160414,-1.09822,-0.269238,1.20704,0.614584,1.19401,-0.144036,-0.43539
12,1993-01-16 00:00:00,-4.45158,-1.41169,-2.17839,-0.861494,0.927779,1.11486,-0.105482,-0.0815978
13,1993-02-16 00:00:00,-8.95834,-1.15978,-3.77888,-4.01969,1.54597,1.57477,-0.145834,0.117031
14,1993-03-16 00:00:00,-6.12057,-0.845827,-2.1765,-3.09824,1.68252,1.78734,-0.180957,0.0761332
15,1993-04-16 00:00:00,-1.35014,-0.434485,0.555642,-1.4713,1.98436,1.67419,-0.0400656,0.350232
16,1993-05-16 00:00:00,-0.821962,-0.546863,1.68064,-1.95573,0.752588,0.785447,0.0566751,-0.0895343
17,1993-06-16 00:00:00,-1.22426,-0.293444,0.399136,-1.32995,0.156863,0.390843,-0.239081,0.00510129
18,1993-07-16 00:00:00,-9.39697,-0.243236,-3.12127,-6.03246,0.847933,0.687659,0.133563,0.0267114
19,1993-08-16 00:00:00,-8.00811,-0.496081,-4.13496,-3.37707,0.00154867,0.765528,-0.439491,-0.324488
20,1993-09-16 00:00:00,-4.38575,-0.310652,0.699445,-4.77455,1.14383,1.09965,-0.326546,0.37072
21,1993-10-16 00:00:00,2.5803,0.338082,4.42903,-2.18682,1.65671,1.28916,0.312467,0.0550776
22,1993-11-16 00:00:00,3.77584,0.658515,3.3729,-0.255573,2.00384,1.00992,0.285175,0.708752
23,1993-12-16 00:00:00,-2.0447,0.281783,-0.30209,-2.0244,2.23192,0.802256,0.545884,0.883781
24,1994-01-16 00:00:00,-1.63932,0.411662,-1.8303,-0.220681,1.29074,0.194098,0.29251,0.804128
25,1994-02-16 00:00:00,-6.42955,-0.0519591,-2.45362,-3.92397,1.3529,0.80432,0.0788825,0.469702
26,1994-03-16 00:00:00,-4.48999,-0.685622,-1.39585,-2.40852,0.856488,1.07609,-0.416932,0.197329
27,1994-04-16 00:00:00,-1.36513,-0.219502,0.685649,-1.83128,-0.302323,0.636542,-1.05247,0.1136
28,1994-05-16 00:00:00,1.00843,-0.0106041,2.05265,-1.03362,-0.517543,0.202649,-0.715181,-0.00501089
29,1994-06-16 00:00:00,1.03806,0.276042,0.360182,0.401836,-1.09939,-0.179672,-0.785192,-0.134531
...,...,...,...,...,...,...,...,...,...
222,2010-07-16 00:00:00,-7.03821,0.00874109,-3.11047,-3.93648,-0.239362,0.376927,0.138567,-0.754856
223,2010-08-16 00:00:00,-2.92928,-0.303575,-1.63635,-0.989351,-0.757899,0.323813,-0.325443,-0.756269
224,2010-09-16 00:00:00,-3.30332,-0.179673,1.86286,-4.98651,-0.00633041,0.539007,-0.394217,-0.151121
225,2010-10-16 00:00:00,2.93407,0.474066,5.69767,-3.23766,0.613783,0.817053,-0.0789709,-0.124299
226,2010-11-16 00:00:00,2.54657,0.812614,2.34349,-0.609537,1.06212,0.653729,0.055805,0.352588
227,2010-12-16 00:00:00,-0.877035,0.144536,0.590414,-1.61199,0.943194,0.62423,-0.0449606,0.363925
228,2011-01-16 00:00:00,-7.16342,-0.743244,-6.66515,0.244974,-0.0157157,0.37483,-0.712306,0.321761
229,2011-02-16 00:00:00,-12.5666,-1.2606,-7.24574,-4.06027,0.363285,0.950748,-0.749833,0.16237
230,2011-03-16 00:00:00,-10.6036,-1.47858,-5.0133,-4.11167,-0.988896,0.809749,-1.57003,-0.228618
231,2011-04-16 00:00:00,-4.09672,-0.925555,-0.146125,-3.02504,-0.5262,0.968252,-1.52967,0.0352158
232,2011-05-16 00:00:00,2.24905,-0.755313,4.26324,-1.25887,0.643184,0.813122,0.0404248,-0.210363
233,2011-06-16 00:00:00,-2.39421,-0.886546,3.46809,-4.97575,-0.637103,-0.457905,-0.0295689,-0.149629
234,2011-07-16 00:00:00,-7.39382,-0.965725,0.163929,-6.59203,-0.320323,0.106128,0.254415,-0.680865
235,2011-08-16 00:00:00,-7.53474,-1.07328,-1.97912,-4.48234,-0.415866,0.356682,0.00303092,-0.775579
236,2011-09-16 00:00:00,-4.48361,-0.487679,0.102827,-4.09876,0.494332,0.575961,-0.0226758,-0.0589528
237,2011-10-16 00:00:00,1.87822,-0.253547,3.60403,-1.47226,1.11235,1.0683,0.0733435,-0.0292906
238,2011-11-16 00:00:00,1.9307,0.2546,0.883621,0.792483,1.61626,1.10029,0.284159,0.231805
239,2011-12-16 00:00:00,-0.690555,-0.131929,1.54561,-2.10423,0.852519,0.816449,-0.0515594,0.0876304
240,2012-01-16 00:00:00,-1.70395,-0.248836,-0.236023,-1.21909,0.318859,0.263994,-0.31425,0.369115
241,2012-02-16 00:00:00,-4.22173,-0.108747,0.167685,-4.28067,0.273959,0.214622,-0.288133,0.34747
242,2012-03-16 00:00:00,-7.6798,-0.91735,-1.24651,-5.51594,-0.302578,0.333495,-0.57347,-0.0626033
243,2012-04-16 00:00:00,-7.18539,-0.722871,-1.8911,-4.57142,-0.622342,0.108622,-0.716129,-0.0148345
244,2012-05-16 00:00:00,-5.32161,-0.818544,-0.825629,-3.67744,-0.552369,0.1253,-0.371106,-0.306563
245,2012-06-16 00:00:00,-5.84752,-0.563275,0.335657,-5.61991,-0.848779,0.358813,-0.629464,-0.578129
246,2012-07-16 00:00:00,-8.10269,-0.0877855,-1.76563,-6.24928,-1.43655,0.310319,-0.701565,-1.0453
247,2012-08-16 00:00:00,-1.62378,0.170679,0.653902,-2.44836,-1.44386,-0.0209059,-0.778964,-0.643987
248,2012-09-16 00:00:00,2.42461,0.591008,3.68024,-1.84664,-0.0598784,0.201129,-0.561353,0.300345
249,2012-10-16 00:00:00,5.79803,0.645212,5.56859,-0.415771,0.950844,0.61579,0.165077,0.169977
250,2012-11-16 00:00:00,0.254643,0.585271,1.99215,-2.32278,1.50741,0.715975,0.545613,0.245826
251,2012-12-16 00:00:00,-0.128614,0.0487807,1.13783,-1.31522,0.832235,0.831748,-0.0425964,0.043083

In [ ]:
%%time

# master_branch
fai.spatial_integration(df, ['Terrestrial_flux','ocean'])

In [5]:
lat = df.latitude
lon = df.longitude

In [6]:
df['ocean'].sel(time=df.time[0])

<xarray.DataArray 'ocean' (latitude: 180, longitude: 360)>
array([[0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       ...,
       [1.256956, 1.256956, 1.256956, ..., 1.256956, 1.256956, 1.256956],
       [1.256957, 1.256957, 1.256957, ..., 1.256957, 1.256957, 1.256957],
       [1.256962, 1.256962, 1.256962, ..., 1.256962, 1.256962, 1.256962]],
      dtype=float32)
Coordinates:
  * longitude  (longitude) float64 -179.5 -178.5 -177.5 ... 177.5 178.5 179.5
  * latitude   (latitude) float64 -89.5 -88.5 -87.5 -86.5 ... 87.5 88.5 89.5
    time       object 1992-01-16 00:00:00
Attributes:
    title:    ocean
    units:    gC/m2/year

In [7]:
ocean = df['ocean'].sel(time=df.time[0]).values
ocean

array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [1.2569561, 1.2569561, 1.2569561, ..., 1.2569561, 1.2569561,
        1.2569561],
       [1.2569572, 1.2569572, 1.2569572, ..., 1.2569572, 1.2569572,
        1.2569572],
       [1.2569623, 1.2569623, 1.2569623, ..., 1.2569623, 1.2569623,
        1.2569623]], dtype=float32)

In [8]:
eag = fai.earth_area_grid(lat, lon)
eag

array([[1.07896236e+08, 1.07896236e+08, 1.07896236e+08, ...,
        1.07896236e+08, 1.07896236e+08, 1.07896236e+08],
       [3.23655841e+08, 3.23655841e+08, 3.23655841e+08, ...,
        3.23655841e+08, 3.23655841e+08, 3.23655841e+08],
       [5.39316857e+08, 5.39316857e+08, 5.39316857e+08, ...,
        5.39316857e+08, 5.39316857e+08, 5.39316857e+08],
       ...,
       [5.39316857e+08, 5.39316857e+08, 5.39316857e+08, ...,
        5.39316857e+08, 5.39316857e+08, 5.39316857e+08],
       [3.23655841e+08, 3.23655841e+08, 3.23655841e+08, ...,
        3.23655841e+08, 3.23655841e+08, 3.23655841e+08],
       [1.07896236e+08, 1.07896236e+08, 1.07896236e+08, ...,
        1.07896236e+08, 1.07896236e+08, 1.07896236e+08]])

In [9]:
eag*ocean

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [6.77897613e+08, 6.77897613e+08, 6.77897613e+08, ...,
        6.77897613e+08, 6.77897613e+08, 6.77897613e+08],
       [4.06821530e+08, 4.06821530e+08, 4.06821530e+08, ...,
        4.06821530e+08, 4.06821530e+08, 4.06821530e+08],
       [1.35621500e+08, 1.35621500e+08, 1.35621500e+08, ...,
        1.35621500e+08, 1.35621500e+08, 1.35621500e+08]])

In [10]:
(eag*ocean)[lat>23]

array([[3.45603863e+10, 3.45603863e+10, 3.45603863e+10, ...,
        2.27681023e+09, 2.27681023e+09, 2.27681023e+09],
       [3.42928657e+10, 3.42928657e+10, 3.42928657e+10, ...,
        2.25918634e+09, 2.25918634e+09, 2.25918634e+09],
       [3.40148938e+10, 3.40148938e+10, 3.40148938e+10, ...,
        2.24087344e+09, 2.24087344e+09, 2.24087344e+09],
       ...,
       [6.77897613e+08, 6.77897613e+08, 6.77897613e+08, ...,
        6.77897613e+08, 6.77897613e+08, 6.77897613e+08],
       [4.06821530e+08, 4.06821530e+08, 4.06821530e+08, ...,
        4.06821530e+08, 4.06821530e+08, 4.06821530e+08],
       [1.35621500e+08, 1.35621500e+08, 1.35621500e+08, ...,
        1.35621500e+08, 1.35621500e+08, 1.35621500e+08]])

In [11]:
nag = fai.earth_area_grid(lat[lat>23], lon)
o = ocean[lat>23]
nag*o

array([[3.45603863e+10, 3.45603863e+10, 3.45603863e+10, ...,
        2.27681023e+09, 2.27681023e+09, 2.27681023e+09],
       [3.42928657e+10, 3.42928657e+10, 3.42928657e+10, ...,
        2.25918634e+09, 2.25918634e+09, 2.25918634e+09],
       [3.40148938e+10, 3.40148938e+10, 3.40148938e+10, ...,
        2.24087344e+09, 2.24087344e+09, 2.24087344e+09],
       ...,
       [6.77897613e+08, 6.77897613e+08, 6.77897613e+08, ...,
        6.77897613e+08, 6.77897613e+08, 6.77897613e+08],
       [4.06821530e+08, 4.06821530e+08, 4.06821530e+08, ...,
        4.06821530e+08, 4.06821530e+08, 4.06821530e+08],
       [1.35621500e+08, 1.35621500e+08, 1.35621500e+08, ...,
        1.35621500e+08, 1.35621500e+08, 1.35621500e+08]])

In [12]:
((eag*ocean)[lat>23]==nag*o)

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [13]:
lat.values

array([-89.5, -88.5, -87.5, -86.5, -85.5, -84.5, -83.5, -82.5, -81.5,
       -80.5, -79.5, -78.5, -77.5, -76.5, -75.5, -74.5, -73.5, -72.5,
       -71.5, -70.5, -69.5, -68.5, -67.5, -66.5, -65.5, -64.5, -63.5,
       -62.5, -61.5, -60.5, -59.5, -58.5, -57.5, -56.5, -55.5, -54.5,
       -53.5, -52.5, -51.5, -50.5, -49.5, -48.5, -47.5, -46.5, -45.5,
       -44.5, -43.5, -42.5, -41.5, -40.5, -39.5, -38.5, -37.5, -36.5,
       -35.5, -34.5, -33.5, -32.5, -31.5, -30.5, -29.5, -28.5, -27.5,
       -26.5, -25.5, -24.5, -23.5, -22.5, -21.5, -20.5, -19.5, -18.5,
       -17.5, -16.5, -15.5, -14.5, -13.5, -12.5, -11.5, -10.5,  -9.5,
        -8.5,  -7.5,  -6.5,  -5.5,  -4.5,  -3.5,  -2.5,  -1.5,  -0.5,
         0.5,   1.5,   2.5,   3.5,   4.5,   5.5,   6.5,   7.5,   8.5,
         9.5,  10.5,  11.5,  12.5,  13.5,  14.5,  15.5,  16.5,  17.5,
        18.5,  19.5,  20.5,  21.5,  22.5,  23.5,  24.5,  25.5,  26.5,
        27.5,  28.5,  29.5,  30.5,  31.5,  32.5,  33.5,  34.5,  35.5,
        36.5,  37.5,  38.5,  39.5,  40.5,  41.5,  42.5,  43.5,  44.5,
        45.5,  46.5,  47.5,  48.5,  49.5,  50.5,  51.5,  52.5,  53.5,
        54.5,  55.5,  56.5,  57.5,  58.5,  59.5,  60.5,  61.5,  62.5,
        63.5,  64.5,  65.5,  66.5,  67.5,  68.5,  69.5,  70.5,  71.5,
        72.5,  73.5,  74.5,  75.5,  76.5,  77.5,  78.5,  79.5,  80.5,
        81.5,  82.5,  83.5,  84.5,  85.5,  86.5,  87.5,  88.5,  89.5])

In [14]:
np.arange(-179.5, 180.5)==lon.values

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [20]:
spa = fai.spatial_integration(df, ['Terrestrial_flux', 'ocean'], time=(0,24))

In [21]:
fai.year_integration(spa)

,Year,earth_land_total,south_land_total,trop_land_total,north_land_total,earth_ocean_total,south_ocean_total,trop_ocean_total,north_ocean_total
0,1992,-29.4476,2.69072,-9.73824,-22.4001,-3.00218,6.11725,-5.81536,-3.30407
1,1993,-40.4063,-4.46368,-4.55531,-31.3873,14.9359,12.9816,-0.143693,2.09792
2,1994,-1.63932,0.411662,-1.8303,-0.220681,1.29074,0.194098,0.29251,0.804128

In [23]:
fai.whole_time_integration(spa)

earth_land_total    -71.493203
south_land_total     -1.361304
trop_land_total     -16.123846
north_land_total    -54.008052
earth_ocean_total    13.224412
south_ocean_total    19.292977
trop_ocean_total     -5.666548
north_ocean_total    -0.402018
dtype: float64